---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: student-java-{{GIT_BRANCH_NAME}}
  labels:
    app: student-java
    branch: {{GIT_BRANCH_NAME}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-java
      branch: {{GIT_BRANCH_NAME}}
  template:
    metadata:
      labels:
        app: student-java
        branch: {{GIT_BRANCH_NAME}}
    spec:
      containers:
      - name: student-java
        image: {{IMAGE_NAME}}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: student-java-{{GIT_BRANCH_NAME}}
  labels:
    app: student-java
    branch: {{GIT_BRANCH_NAME}}
spec:
  selector:
    app: student-java
    branch: {{GIT_BRANCH_NAME}}
    type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
