---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: student-java-master
  labels:
    app: student-java
    branch: master
    env: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-java
      branch: master
  template:
    metadata:
      labels:
        app: student-java
        branch: master
    spec:
      containers:
      - name: student-java
        image: {{IMAGE_NAME}}
        ports:
        - containerPort: 8080
