# H2
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:tech_training;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

info:
  app:
    name: Spring boot java app
    version: 1.0.4
---
spring:
  profiles:
    active: prod
